linters:
  disable:
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - interfacer
    - maligned
    - nlreturn
    - paralleltest
    - prealloc
    - unparam
    - wrapcheck
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused

linters-settings:
  wsl:
    allow-cuddle-declarations: true

run:
  skip-dirs:
    - web
